# Generated by Django 4.2.1 on 2023-06-02 12:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Не должно быть меньше минуты!')], verbose_name='Время готовки')),
                ('description', models.TextField(help_text='Введите описание рецепта', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='recipes/')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient', verbose_name='Ингредиенты')),
                ('tag', models.ManyToManyField(to='recipes.tag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='IngredientIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Не должно быть меньше 1')])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsrecipes', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsrecipes', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Ингредиент рецепта.',
                'verbose_name_plural': 'Ингредиенты в рецепте.',
            },
        ),
        migrations.AddConstraint(
            model_name='ingredientin',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_ingredientin'),
        ),
    ]
