# Generated by Django 4.2.1 on 2023-06-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_unit_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
